# Generated by Django 4.0.4 on 2022-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('Gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('emailid', models.EmailField(max_length=50)),
                ('Address', models.TextField(max_length=225)),
                ('hobbies', models.CharField(max_length=100)),
                ('languages_known', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('objective', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'personal_info',
            },
        ),
    ]
