# Generated by Django 4.0.4 on 2022-06-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academic_project',
            table='academic_project',
        ),
    ]
