# Generated by Django 4.0.4 on 2022-06-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_personal_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='phone_number',
        ),
    ]
