# Generated by Django 4.0.4 on 2022-06-25 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_remove_personal_info_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='educational_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfExamination', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=10)),
                ('perIn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.personal_info')),
            ],
            options={
                'db_table': 'educational_details',
            },
        ),
    ]
