# Generated by Django 4.0.4 on 2022-06-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_educational_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=100)),
                ('perIn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.personal_info')),
            ],
        ),
    ]
